"""initial fresh start

Revision ID: d4a8e26cb016
Revises:
Create Date: 2026-02-17 18:53:03.871715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d4a8e26cb016"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nik", sa.String(length=20), nullable=False),
        sa.Column("nama", sa.String(length=100), nullable=False),
        sa.Column("sex", sa.String(length=1), nullable=False),
        sa.Column("tgl_lahir", sa.Date(), nullable=False),
        sa.Column("umur", sa.Integer(), nullable=True),
        sa.Column("umur_rekrut", sa.Integer(), nullable=True),
        sa.Column("tempat_lahir", sa.String(length=100), nullable=False),
        sa.Column("no_ktp", sa.String(length=16), nullable=False),
        sa.Column("no_kk", sa.String(length=16), nullable=True),
        sa.Column("no_hp", sa.String(length=15), nullable=True),
        sa.Column("alamat", sa.Text(), nullable=True),
        sa.Column("kelurahan", sa.String(length=100), nullable=True),
        sa.Column("kecamatan", sa.String(length=100), nullable=True),
        sa.Column("kabupaten_kota", sa.String(length=100), nullable=True),
        sa.Column("kode_pos", sa.String(length=10), nullable=True),
        sa.Column("provinsi", sa.String(length=100), nullable=True),
        sa.Column("status_kawin", sa.String(length=20), nullable=True),
        sa.Column("tanggungan", sa.Integer(), nullable=False),
        sa.Column("agama", sa.String(length=50), nullable=True),
        sa.Column("tinggi_badan", sa.Float(), nullable=True),
        sa.Column("berat_badan", sa.Float(), nullable=True),
        sa.Column("gol_darah", sa.String(length=2), nullable=True),
        sa.Column("pendidikan", sa.String(length=100), nullable=True),
        sa.Column("tgl_rekrut", sa.Date(), nullable=False),
        sa.Column("status_karyawan", sa.String(length=20), nullable=True),
        sa.Column("tgl_kartetap", sa.Date(), nullable=True),
        sa.Column("posisi_karyawan", sa.String(length=100), nullable=True),
        sa.Column("no_kartu_kpk", sa.String(length=50), nullable=True),
        sa.Column("group", sa.String(length=100), nullable=True),
        sa.Column("dept", sa.String(length=100), nullable=True),
        sa.Column("jabatan", sa.String(length=100), nullable=True),
        sa.Column("kontrak_ke", sa.Integer(), nullable=False),
        sa.Column("kontrak_berakhir", sa.Date(), nullable=True),
        sa.Column("remaining", sa.Integer(), nullable=True),
        sa.Column("kode_gaji", sa.String(length=50), nullable=True),
        sa.Column("no_rek_bank", sa.String(length=30), nullable=True),
        sa.Column("kode_bank", sa.String(length=10), nullable=True),
        sa.Column("transfer_cash", sa.String(length=10), nullable=True),
        sa.Column("nama_bank", sa.String(length=100), nullable=True),
        sa.Column("status_ptkp", sa.String(length=20), nullable=True),
        sa.Column("no_npwp", sa.String(length=20), nullable=True),
        sa.Column("bpjs_tk", sa.Boolean(), nullable=False),
        sa.Column("bpjs_tk_ditanggung", sa.String(length=50), nullable=True),
        sa.Column("bpjs_tk_no", sa.String(length=30), nullable=True),
        sa.Column("bpjs_kes", sa.Boolean(), nullable=False),
        sa.Column("bpjs_kes_ditanggung", sa.String(length=50), nullable=True),
        sa.Column("bpjs_kes_no", sa.String(length=30), nullable=True),
        sa.Column("status_pajak", sa.String(length=10), nullable=True),
        sa.Column("faskes", sa.String(length=100), nullable=True),
        sa.Column("placement", sa.String(length=100), nullable=True),
        sa.Column("tgl_out", sa.Date(), nullable=True),
        sa.Column("lama_bekerja", sa.Integer(), nullable=True),
        sa.Column("status_kerja", sa.String(length=10), nullable=True),
        sa.Column("foto", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_employees_nik"), "employees", ["nik"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_index(op.f("ix_employees_nik"), table_name="employees")
    op.drop_table("employees")
    # ### end Alembic commands ###
